### ISSUE TITLE
Check if correct version on JAVA is used

### ISSUE THREAD

**Issue by GegznaV** [nevrome/LanguageToolR#11]
On my PC, the following command line code results in JAVA exception/Error, if 32-bit JAVA is used.

```bash
java -jar "D:/Dokumentai/LanguageTool-4.6/languagetool-commandline.jar" --encoding utf-8 --language en-GB --json "inst/test/test_text.txt"
```

<details>
<summary><i>(The output)</i></summary>

```
Warning: At the moment, your platform (Windows) is not supported by the official XGBoost maven package; ML-based suggestion reordering is disabled.
Expected text language: English (GB)
Working on inst/test/test_text.txt...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:153)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:738)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:716)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:699)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:658)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:642)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:106)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:82)
        at org.languagetool.commandline.Main.runOnFile(Main.java:194)
        at org.languagetool.commandline.Main.main(Main.java:466)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.ForkJoinTask.get(Unknown Source)
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:146)
        ... 9 more
Caused by: java.lang.OutOfMemoryError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        ... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at opennlp.tools.ml.model.AbstractModelReader.getParameters(AbstractModelReader.java:140)
        at opennlp.tools.ml.maxent.io.GISModelReader.constructModel(GISModelReader.java:78)
        at opennlp.tools.ml.model.GenericModelReader.constructModel(GenericModelReader.java:62)
        at opennlp.tools.ml.model.AbstractModelReader.getModel(AbstractModelReader.java:85)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:32)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:29)
        at opennlp.tools.util.model.BaseModel.finishLoadingArtifacts(BaseModel.java:309)
        at opennlp.tools.util.model.BaseModel.loadModel(BaseModel.java:239)
        at opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:173)
        at opennlp.tools.postag.POSModel.<init>(POSModel.java:82)
        at org.languagetool.chunking.EnglishChunker.<init>(EnglishChunker.java:64)
        at org.languagetool.language.English.getChunker(English.java:136)
        at org.languagetool.JLanguageTool.getRawAnalyzedSentence(JLanguageTool.java:991)
        at org.languagetool.JLanguageTool.getAnalyzedSentence(JLanguageTool.java:966)
        at org.languagetool.MultiThreadedJLanguageTool$AnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:208)
        at org.languagetool.MultiThreadedJLanguageTool$AnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:199)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
</details>

<details>
I also asked a question about this kind of output (JAVA  out of the memory issue) on Windows: languagetool-org/languagetool#1813 and got answer, that there is a way to solve it by adding additional lines of code, but [here](https://forum.languagetool.org/t/resolved-xgboost-warning-and-outofmemoryerror-when-checking-english-with-ngram/4539/2) is reported that similar issue was solved only by upgrading to 64-bit JAVA.
</details>

Could we include a function that correctly identifies this issue and creates a meaningful warning?

We can start with something like this:

```r
# Check if 64-bit JAVA is used.
# Based on https://stackoverflow.com/a/38154064/4783029
lato_is_java_64bit <- function() {
  str1 <- system("java -XshowSettings:properties -version", intern = TRUE, ignore.stderr = FALSE)
  str2 <- gsub(".*sun.arch.data.model = (.*)", "\\1", str1[grepl("sun.arch.data.model = ", str1)])
  str2 == 64
}
```
 Based on https://stackoverflow.com/a/38154064/4783029

This error is related to JAVA: 64-bit version of JAVA should be used to prevent the error.

Maybe checking if a correct version of JAVA is used could be performed and a meaningful warning displayed if needed?

**Comment by nevrome** [comment]
A bit more simple: 

```
lato_is_java_64bit <- function() {
  java_version_output <- system2("java" , c("-XshowSettings:properties", "-version"), stderr = TRUE, stdout = TRUE)
  return(any(grepl("sun.arch.data.model = 64", java_version_output)))
}
```

We could call this at the beginning of `lato_quick_setup()`.
